### ISSUE TITLE
Support for 'gemengde plastics'

### ISSUE THREAD

**Issue by elRadix** [pippyn/Home-Assistant-Sensor-Ophaalkalender#1]
It is once per month that they collect the plastics, seems not on your list

![image](https://user-images.githubusercontent.com/6258894/53903789-e4ace280-4044-11e9-898a-fe58dffdcbf6.png)

**Comment by pippyn** [comment]
Can you provide some information to test with?
street name, street number, postcode?

**Comment by elRadix** [comment]
post code xxx 
street xxx

it's always once per month, next one is 4th of May

**Comment by pippyn** [comment]
When I add `- gemengde plastics` to the resources it works for me. Does your sensor give an error? Did you make a spelling error?

**Comment by elRadix** [comment]
i did not all the resources, maybe the name of the resource is different, all add all of them and check

**Comment by elRadix** [comment]
works now - was not mentioned in the readme file 
seems not all sensors are updated

![image](https://user-images.githubusercontent.com/6258894/53951608-21bdb700-40cf-11e9-9ca9-63eb56d7b75b.png)

**Comment by pippyn** [comment]
Usually the sensors that are unknown are fractions that are not collected in your area. Is that the case?

**Comment by elRadix** [comment]
I do see grof and snoeiafval (tuinafval) listed below

**Comment by pippyn** [comment]
Change your config for the 2 sensors to;
```
recources:
  - grof huisvuil afroep
  - snoeiafval afroep
```
If that works I'll post a fix later today

**Comment by elRadix** [comment]
works now

![image](https://user-images.githubusercontent.com/6258894/53954821-9694ef00-40d7-11e9-8357-76d58a9765ba.png)
