### ISSUE TITLE
HA crash

### ISSUE THREAD

**Issue by ezieleman** [pippyn/Home-Assistant-Sensor-Ophaalkalender#14]
When adding the following to configuration.yaml HA won't start any more
- platform: ophaalkalender
      resources:
        - restafval
        - tuinafval
        - papier
        - pmd
        - grofafval
      postcode: 1111
      streetname: straatnaam	
      streetnumber: 10

Any one else this issues? running latest version of HA and latest version of plugin

thanx

**Comment by pippyn** [comment]
HA will not start? at all? That cannot be an issue with this component. If the component is not working correctly HA will disable the component/ give an error when restarting.

**Comment by pippyn** [comment]
Due to no response, this issue will be closed
