### ISSUE TITLE
Status unknown

### ISSUE THREAD

**Issue by RutgerP** [pippyn/Home-Assistant-Sensor-Ophaalkalender#15]
sensor:
  - platform: ophaalkalender
    resources:
      - restafval
      - tuinafval
      - papier
      - pmd
      - grofafval
    postcode: '2100'
    streetname: 'schotensesteenweg'
    streetnumber: '160'

Could you look into this?

**Comment by nudded** [comment]
FYI: this is usually every year the same issue with ophaalkalender.be 
Their data is simply not present yet for the new year. You should bug them about it ;)

**Comment by RutgerP** [comment]
> FYI: this is usually every year the same issue with ophaalkalender.be
> Their data is simply not present yet for the new year. You should bug them about it ;)

Alright thanks for the info!
