### ISSUE TITLE
No 'glas' available

### ISSUE THREAD

**Issue by wimpie007** [pippyn/Home-Assistant-Sensor-Ophaalkalender#18]
Hi,
is it possible to add 'glas'?
Probably not used everywhere, but where i live, there's a section 'glas' also.
![image](https://user-images.githubusercontent.com/33153228/71826716-d5e8ef00-309e-11ea-84d3-f0cfdc75b7b6.png)

(Yellow with white letters, almost impossible to read, but is says 'glas' )

**Comment by pippyn** [comment]
It should work. Do you have streetnumber, postal code and streetname for me so I can test it?

**Comment by wimpie007** [comment]
You're right! didn't see 'glas' in the example!
just added 
    resources:
      - restafval
      - tuinafval
      - papier
      - pmd
      - grofafval
      **- glas**
and it worked right away!
Great, thanks!!
