### ISSUE TITLE
Connection error Ophaalkalender.be

### ISSUE THREAD

**Issue by Depechie** [pippyn/Home-Assistant-Sensor-Ophaalkalender#19]
So I have a test Hassio install where I try out new Home Assistant updates and custom components. I recently updated to HA 0.103.5 and installed the Ophaalkalendar component through HACS.
All works fine for my town/street.

So enter my actual Home Assistant install, this is still a Hasbian install - but also on HA 0.103.5. I manually install the custom component but I can't get it to work... always get:

`Error occurred while fetching data: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'www.ophaalkalender.be\', port=443): Max retries exceeded with url: /calendar/findstreets/?query=`

Of course I first stopped/disabled the component in the Hassio install and also waited several hours to retry in Hasbian.
Opening the website of Ophaalkalender.be directly and entering my street there also just works.

Any tips?

**Comment by Depechie** [comment]
The hassio is not running HTTPS of course ( it's a test install for try outs ), but the Hasbian is running with SSL.

**Comment by pippyn** [comment]
I'm not sure. It's working for me. Maybe an error in indentation?

**Comment by Depechie** [comment]
Don't think so... but will double check.
The query in the log contains the actual address, in other words I would assume the Yaml is correct.

Is there a way I can run some script through SSH on the raspberry pi itself ( a curl or something ) to simulate the request?

**Comment by pippyn** [comment]
Yes you can, but it's not easy to explain. Could you give me a street name, postcode and house number for me to test with? somewhere in your neighborhood should be fine.

**Comment by Depechie** [comment]
Could be something with my setup of course, the actual error is :
`OpenSSL.SSL.Error: [('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')]`
Most google searches point to SSL certificates.

Anyhow, try
Zijpstraat 100, 2570

**Comment by Depechie** [comment]
Did some linux tests...
`curl https://www.ophaalkalender.be -v`

Gives
```
* Connected to www.ophaalkalender.be (81.246.112.169) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS alert, protocol version (582):
* error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
* Closing connection 0
curl: (35) error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
```

And
 `curl --tlsv1.3 https://www.ophaalkalender.be -v`

Gives
```
* Connected to www.ophaalkalender.be (81.246.112.169) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.ophaalkalender.be:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.ophaalkalender.be:443
``` 

So no matter what I try with curl, I get some SSL error. It does change when I force tls v1.3 but the syscal error is also not good.
I'm no SSL expert so no clue where the actual problem can reside.

**Comment by pippyn** [comment]
I'm also no SSL expert. All I can say is the information you've given me works for me. This looks like a wider issue in your setup.

**Comment by pippyn** [comment]
Due to no response, this issue will be closed
