### ISSUE TITLE
address not found

### ISSUE THREAD

**Issue by NimdaBE** [pippyn/Home-Assistant-Sensor-Ophaalkalender#22]
Hello,

i just started with Hassio (hassos 3.8 and Home Assistant 0.104.3) and i installed ophaalkalender 1.1.4 via HACS. When i try to set up the sensor in my configuration.yaml i get an "address not found" error in the logs.

> 2020-01-29 12:14:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ophaalkalender which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2020-01-29 12:14:47 ERROR (SyncWorker_0) [custom_components.ophaalkalender.sensor] Address not found!

The address i'm using is zipcode 9450, Fonteinstraat 13. There is data when i enter this address on the website (https://www.ophaalkalender.be/Calendar).

I tried different formatting for the streetname (lowercase, uppercase, with or without 
municipality name between brackets (as the site shows when you select the street name), but i still get this error...

**Comment by pippyn** [comment]
What does the config look like?

**Comment by NimdaBE** [comment]
> sensor:
    - platform: ophaalkalender
      resources:
        - restafval
        - tuinafval
        - papier
        - pmd
        - grofafval
      postcode: 9540
      streetname: Fonteinstraat
      streetnumber: 13

this is what i have in my config (i checked indention, as pasting it here screws the formatting)

**Comment by pippyn** [comment]
Past it as code please. that will preserve the indentation.
(the <> button)

**Comment by NimdaBE** [comment]
`sensor:
  - platform: ophaalkalender
    resources:
      - restafval
      - tuinafval
      - papier
      - pmd
      - grofafval
    postcode: 9540
    streetname: Fonteinstraat
    streetnumber: 13
`
formatting is still wonky when pasting it... in my configurator everything looks fine (even counted spaces etc...)

**Comment by pippyn** [comment]
Oke, nevertheless it should be this:
```
- platform: ophaalkalender
  resources:
    - restafval
    - tuinafval
    - papier
    - pmd
    - grofafval
  postcode: 9540
  streetname: Fonteinstraat
  streetnumber: 13
```
Can you confirm this is what you have?

**Comment by NimdaBE** [comment]
yes, but it's all wrapped in a sensor (exactly like the example config on your github page)

**Comment by pippyn** [comment]
I tried ophaalkalender.be and it says:

> De ophaalkalender is niet beschikbaar voor de postcode die je ingegeven hebt.
> Er zijn twee mogelijkheden:
> 1. Je hebt de postcode van een deelgemeente ingegeven. Probeer eens opnieuw met de postcode van de hoofdgemeente.
> 2. Jouw afvalintercommunale neemt niet deel aan dit project.

**Comment by NimdaBE** [comment]
when i go to https://www.ophaalkalender.be/Calendar and i enter 9450 as postcode (which is the main postcode) and i select my street and number i see the calendar...

**Comment by pippyn** [comment]
You have the wrong postcode in your config then...
You have 9540 in stead of 9450

**Comment by NimdaBE** [comment]
O. M. G... I hereby give you permission to slap me for being stupid... I made a typo and kept looking over it over and over again and focussing too much on indention and other stuff....

my apologies for wasting your time...

**Comment by pippyn** [comment]
No problem :) Glad I could help.
Have fun discovering HA!
