### ISSUE TITLE
wrong date for paper

### ISSUE THREAD

**Issue by benutti** [pippyn/Home-Assistant-Sensor-Ophaalkalender#26]
I tried to configure it for my postal code 8650 and got a date for paper that's set to december (we're april now)
ophaalkalender restafval
Thursday, 16-04-2020
ophaalkalender papier
24-12-2020
ophaalkalender pmd
24-04-2020

**Comment by benutti** [comment]
I tried to configure it for my postal code 8650 and got a date for paper that's set to december (we're april now)
ophaalkalender restafval
Thursday, 16-04-2020
ophaalkalender papier
24-12-2020
ophaalkalender pmd
24-04-2020

**Comment by pippyn** [comment]
Do you have a postal code, street name and street number for me to test with?

In the meantime you can test my other sensor [Afvalbeheer](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer), the code is more up to date and has more options. This sensor is going to deprecate later this month.

**Comment by benutti** [comment]
8650 Beukhoutstraat 38

**Comment by pippyn** [comment]
You are right. I'm not sure why it displays the wrong date.

But I'm not going to fix this bug because:
- Afvalbeheer does display the correct date
- This sensor is deprecated later this week.

I would recommend to switch to Afvalbeheer

**Comment by benutti** [comment]
already did , thanks :)
