### ISSUE TITLE
add component to HACS

### ISSUE THREAD

**Issue by aaamoeder** [pippyn/Home-Assistant-Sensor-Ophaalkalender#5]
Hey there, love the component !

It would be great if you could issue a PR for it to be added to HACS 
(https://custom-components.github.io/hacs/developer/include_default_repositories/)
As far as I can see it passes all requirements.

Keep up the great work !

**Comment by pippyn** [comment]
Thank you for your kind words!
Have made a pr.

**Comment by pippyn** [comment]
My pull request is merged and the 3 sensors will be added to the HACS store.

**Comment by aaamoeder** [comment]
Wow that was fast ! Thanks again !
