### ISSUE TITLE
tuinafval gives unknown status

### ISSUE THREAD

**Issue by CervDotBe** [pippyn/Home-Assistant-Sensor-Ophaalkalender#6]
Hi ,

tuinafval results in uknown sensor status. All others work. However, also a minor issue is that PMD results in an other date output than the others. It also gives the weekday.

![image](https://user-images.githubusercontent.com/29871395/62856085-3c3a3300-bcf4-11e9-8d8d-1450211a1fb5.png)

`  - platform: ophaalkalender
    resources:
      - restafval
      - tuinafval
      - papier
      - pmd
    postcode: xxxx
    streetname: xxxx
    streetnumber: x`

Kind Regards,
Robin

**Comment by pippyn** [comment]
Do you have a street number and postcode for me to test with?

**Comment by vanwinkelseppe** [comment]
I know from my city that it is not available. We only have 'gft' and then 'tuinafval' is actually 'snoeiafval'.

Not sure if the same issue, but perhaps it can help you @pippyn 

![image](https://user-images.githubusercontent.com/9077926/63580775-ceb0c100-c595-11e9-95f1-87a0604d4295.png)
Example of postal: 2530 - Street: Dorpsplaats

A lot of cities use different kind of 'waste'.

**Comment by pippyn** [comment]
Yes every city can name their fractions the way they want.. really annoying. Please visit the website and look at the naming of the fractions. Check if they are the same in your config. If it’s not working, give me a postcode, streetname and housenumber in your erea. So I can test

**Comment by CervDotBe** [comment]
Yeah it works when using GFT as parameter. Thanks for the tip @Kieken72 

Zipcode 2220
