### ISSUE TITLE
Sensors give wrong Dates

### ISSUE THREAD

**Issue by bverhalleman** [pippyn/Home-Assistant-Sensor-Ophaalkalender#7]
As the date results of the api are sometimes not ordered, the component gives the first date in the list that > today. 
![test](https://user-images.githubusercontent.com/35332917/64112285-4c8b7e00-cd87-11e9-8848-a057a4ff2e55.jpg)

it can be solved by adding waste_dict[fraction].sort() in the get_next_collection method.
![sol](https://user-images.githubusercontent.com/35332917/64112532-fe2aaf00-cd87-11e9-904a-86f0c45ddab0.JPG)

**Comment by Friedrieck** [comment]
+1!
I had this issue, with next collections reported to be in December 2020.
Your fix did the trick, thank you!
@pippyn, please consider including this fix in a next release.

**Comment by pippyn** [comment]
You are right. Added the fix

**Comment by tr1plus** [comment]
It seems even downloading the latest version (re-install via HACS) didn't fix this issue. I am still getting dates reported end of feb, but the garbage is coming next wednessday again :)

EDIT: manually doing the fix mentioned above resolves it. HACS doesn't take the latest version yet?
