### ISSUE TITLE
Plastic Collection  "Gemengde plastics" (Pink Collection Bags)

### ISSUE THREAD

**Issue by Pinni3** [pippyn/Home-Assistant-Sensor-Ophaalkalender#8]
Could you please add the "Gemengde plastics" .
this is a special pick up for the Pink bags that are used for plastic recycling.

**Comment by pippyn** [comment]
I'll have a look. Do you have a postcode and street number for me to test with?

**Comment by Pinni3** [comment]
3350 = Postcode
Street = Kapelstraat
do not know how to fetch the streetNR

**Comment by Pinni3** [comment]
![image](https://user-images.githubusercontent.com/30505977/64762972-607d6f80-d53f-11e9-963d-d1390287e4f9.png)
This is the only thing i see in the header when i check the request.

**Comment by Pinni3** [comment]
Issue can be closed.
I used the following and it was working perfect.
  - platform: ophaalkalender
    resources:
        - restafval
        - GFT
        - papier
        - pmd
        - Grof huisvuil afroep
        - Metalen afroep
        **- Gemengde plastics**
