### ISSUE TITLE
possibility to show date prefixes as tomorrow, today, .. in dutch 

### ISSUE THREAD

**Issue by aaamoeder** [pippyn/Home-Assistant-Sensor-Ophaalkalender#9]
As mentioned before.. LOVE the component, works like a charm !

Now I'm working on a home dashboard and it would be nice to be able to show the words like tomorrow, today, days of the week, .. in dutch..

Even if I set the UI (in user settings) to dutch it stays in english..

Thanks in advance !

**Comment by pippyn** [comment]
This feature will be added shortly. But I cant give you an eta.

**Comment by aaamoeder** [comment]
Thanks a lot ! No rush ;)

**Comment by ghust** [comment]
Any update? ;) 

or a simple "days until next" would be great!

**Comment by Friedrieck** [comment]
> .. in dutch

or in French (and German)... it would be highly appreciated!

**Comment by pippyn** [comment]
I integrated ophaalkalender.be in the dutch sensor. So you can use all the features and possibilities of that sensor with ophaalkalender now. Just install "Home Assistant Sensor Afvalbeheer" through HACS or manually via [this link](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer). And configure the sensor. Let me know what you think!

When all works fine this repo is going to deprecate and all further development will be done on the other sensor.
